### ISSUE TITLE
The exception unknown software exception (0xe0434352) occured in the application at location 0x762ac54f

### ISSUE THREAD

**Issue by kenja0** [Labreezy/rev2-wakeup-tool#1]
Error Code: The exception unknown software exception (0xe0434352) occured in the application at location 0x762ac54f.

I followed the instructions and input the code "!8" (no quotations) but the program crashes when I click Enable. The dummy doesn't populate a character.

Running on:
Windows 7
.Net 4.6.2

**Comment by Labreezy** [comment]
Thank you for reporting this issue.  Have you downloaded beta 2 AKA 0.1.1 yet?  It should provide less cryptic error information as well some bugfixes.

Although, it wouldn't catch the dummy never populating and then getting an exception on enabling.  I've seen that issue before and I'm not quite sure what causes it.  Try running beta 2 as an administrator, and see if that fixes things/gives you a different error message.

**Comment by kenja0** [comment]
Beta 2 is what I'm using. The error still populates as Admin. I did this only my Desktop,so I downloaded it to my Laptop (Windows 10, .Net 4.7) to run another test and that crashes upon opening up the program instead.

Are all the files supposed to stay separated in their own folder or do they all need to be in the same location?

**Comment by kenja0** [comment]
What programs do I need to have installed on my PC to run this program?
Will .Net 4.6.2 suffice?
Do I need Visual Studio? What version?
Do i need Wakeup Tool v0.1 AND v0.1.1?
Do I have to enable anything on Rev 2's side so it can talk to the program?
Do I only need to open GGXrdWakeupDPUtil (Application: 41k)?

**Comment by Labreezy** [comment]
All the .dlls you need are included with the release.

Any .NET 4.0 or higher will do.

You do not need visual studio unless you feel like building from source/contributing (won't change anything at the moment if you build from source)

v0.1.1 is the preferred version, as a general rule, keep up with the latest release.

All you have to do is be in training mode, paused when you start the program.

Yes, that's the only one you need to open.

**Comment by Labreezy** [comment]
Also, everything in the release .zip needs to stay in the same folder, but it doesn't matter where it's placed, as long as you can access it.

**Comment by JaxasScarlet** [comment]
I'm having the same issue, however it seems to only display the error message when I try to use Slot 2 or Slot 3. Clicking "Enable" on slot one simply closes the window.
Also, the "Current Dummy" is never populating.

OS: Windows 7 (x64)
Program Version: 0.1.1
.NET Versions: 4.5.1, 4.5.2, 4.6, 4.6.1 (Multi-Targeting, Targeting Packs, SDKs, etc for each)
Filepath: "E:\Games\- Mods, Add-Ons, and Misc\GG Xrd Rev 2 - Wakeup Tool [v0.1.1]" (has also been tested in "C:\test", no change)

Tests:
- Administrator Mode does not fix the problem
- Tested Elphelt VS Sol, as well as Ky VS Sol
- Tested P1 control, Recording Standby, and Active Recording

Error Code: 
CiceroUIWndFrame: GGXrdWakeupDPUtil.exe - Application Error
---------------------------
The exception unknown software exception (0xe0434352) occurred in the application at location 0x7615c54f.


Let me know if you need more info; thanks!

**Comment by oryxcallotis** [comment]
Same issues, usually closes immediately, but the rare times the program opens the dummy never populates with a name and will just crash with an exception error very quickly. Sad, seems like a good tool.

**Comment by Labreezy** [comment]
Fixed, program no longer relies on frida which only worked on windows 10, should work for everyone now.
