### ISSUE TITLE
Broken in xrdr2.1

### ISSUE THREAD

**Issue by raisedbyfinches** [Labreezy/rev2-wakeup-tool#5]
The latest patch has broken 0.1.1 release.

**Comment by raiden17171** [comment]
Yes plz i couldn't open it 2.. can you fix it plz :(

**Comment by Iquis** [comment]
Yup the Rev2.1 broke the release. I could give an hand if somebody could help me with memory adresses, offsets, etc

**Comment by Labreezy** [comment]
Fixed, thank you lquis.
